
-- 1) Total Revenue generated by male vs female customer?
-- select sum(purchase_amount) as revenue, gender
-- from customer
-- group by gender;


-- 2) which customer used a discount but still spent more than a average purchase amount?
-- select customer_id, purchase_amount
-- from customer 
-- where discount_applied='Yes' and purchase_amount>= (
-- 													select avg(purchase_amount)
--                                                     from customer);

-- 3) What are the top 5 products with highest average review rating?
-- select round(avg(review_rating),2) as "Average Product Rating" , item_purchased
-- from customer
-- group by item_purchased
-- order by avg(review_rating) desc
-- limit 5;


-- 4)Compare the average purchase amount between standard and express shipping?
-- select shipping_type, round(avg(purchase_amount),2) as 'Average Purchase Amount'
-- from customer
-- where shipping_type in ('Standard','Express')
-- group by shipping_type;

-- 5)Do subscribed customer spend more? Compare average speed and total revenue between subscribed and non-subscribed customer.
-- select subscription_status,round(avg(purchase_amount),2) as 'Average amount spent', sum(purchase_amount) as 'Total amount spent', count(customer_id) 
-- from customer 
-- where subscription_status in ('Yes','No')
-- group by subscription_status;

-- 6) which 5 products have the highest percentage of purchase with discount applied?
-- select item_purchased, round(100 * sum(case when discount_applied='Yes' then 1 else 0 end)/count(*) ,2) as 'Discount_rate'
-- from customer
-- group by item_purchased
-- order by Discount_rate desc
-- limit 5;

-- 7) Segment customers into new, returing and loyal based on their total no of previous purchases and show the count of each segment.
-- with customer_type as(
-- select customer_id, previous_purchases, 
-- case
-- 	when previous_purchases=1 then "New Customer"
--     when previous_purchases between 2 and 10 then "Returning Customer"
--     else "Loyal Customer" 
--     end as customer_segment
-- from customer
-- )
-- select customer_segment, count(*) as 'Number of Customers'
-- from customer_type
-- group by customer_segment;


-- 8) What are the top 3 most purchased products within each category? 
-- with product_category as(
-- select category, item_purchased, count(customer_id) as total_orders,
-- row_number() over(partition by(category) order by count(customer_id) desc) as item_rank
-- from customer
-- group by category, item_purchased)

-- select item_rank, category, item_purchased, total_orders
-- from product_category
-- where item_rank<=3;

-- 9)Are customer who are repeat buyers (more than 5 previous purchases ) also likely to subscribe?
-- select subscription_status, count(customer_id) as "Repeat Buyers"
-- from customer
-- where previous_purchases>5
-- group by subscription_status


-- 10)What is the revenue contribution of each group? 
select sum(purchase_amount) as 'Total_Revenue', age_group
from customer
group by age_group
order by Total_Revenue desc






